### ISSUE TITLE
Generation of temporary file is a bit too entusiastic

### ISSUE THREAD

**Issue by Drup** [OlivierNicole/ocaml#7]
After compiling a macro switch and some opam stuff, I found my `/tmp` filled with a lot of `cmm` files .. I think the compiler should at least clean after himself, or put things in a subdirectory. :)

**Comment by OlivierNicole** [comment]
Indeed, I completely overlooked this…

**Comment by OlivierNicole** [comment]
Fixed by b1105b56e4ef95b1c03e1a7e. Thanks for reporting :)

**Comment by OlivierNicole** [comment]
In fact, temp files were not wiped in some situations. Should be fixed this time (b0527914098f8d894025b02b3dd6100a3d6fddeb and d5d02ba9a432fabaa479e882aaddfd7)
